/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoleteriaRouteImport } from './routes/boleteria'
import { Route as IndexRouteImport } from './routes/index'

const BoleteriaRoute = BoleteriaRouteImport.update({
  id: '/boleteria',
  path: '/boleteria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boleteria': typeof BoleteriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boleteria': typeof BoleteriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boleteria': typeof BoleteriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boleteria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boleteria'
  id: '__root__' | '/' | '/boleteria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoleteriaRoute: typeof BoleteriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boleteria': {
      id: '/boleteria'
      path: '/boleteria'
      fullPath: '/boleteria'
      preLoaderRoute: typeof BoleteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoleteriaRoute: BoleteriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
