name: Tests TP 6
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        working-directory: Trabajos_practicos/Trabajos_evaluables/TP_6
        run: bun install
      - name: Run tests
        working-directory: Trabajos_practicos/Trabajos_evaluables/TP_6
        run: bun run test
